# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GitHub Pages

on:
  push:
    branches:
      -  master

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          git config user.name "Guilherme Edinger"
          git config user.email "guilherme@edinger.com.br"
          npm ci
          npm run deploy
